### PR TITLE
Attempt to fix the version pinning

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by bsipocz** [comment]
@Cadair - is this good to go?

**Comment by Cadair** [comment]
I think so, but I can't actually test it with SunPy :see_no_evil: I think @jhunkeler might be on the case from speaking to Nadia on chat.

**Comment by bsipocz** [comment]
OK, I'll leave it to him then to merge.

**Comment by jhunkeler** [comment]
Thanks @Cadair

**Pull request merged**
