### PR TITLE
Release asdf 2.5.2 and remove dependency on six

### PR DESCRIPTION
**Pull request by eslavich**
Checklist
* [✓] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [✓] Reset the build number to `0` (if the version changed)
* [✓] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [✓] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @eslavich! 

As a heads up, after you do a release on pypi, there is no need to open a PR on conda-forge, a bot will do it in a bit of time.

**Comment by bsipocz** [comment]
Oh, a bit premature merge from my side. I suppose you should be added as a recipe maintainer, and remove Dan? Let me know and I'm happy to do the changes.

**Comment by eslavich** [comment]
I figured I needed a manual PR this time around to drop the `six` dependency?  Or is the bot clever enough to figure that out on its own?

I'd be happy to serve as a recipe maintainer.  I don't think Dan is involved anymore, so he can probably be removed.

**Comment by bsipocz** [comment]
Yes, the bot is still not clever to update the dependencies, but then recipe maintainers can go into those PRs and adjust the dependencies manually.

**Pull request merged**
